language-file: "lang-en.yml"

spawn-uses-current-world: false

per-world-permissions: false

rtp-cooldown: 60

worlds:
  wilderness:
    type: "NORMAL"
    environment: "NORMAL"
    seed: []
    generate-structures: true
    pvp: true
    difficulty: "HARD"
    spawn-monsters: true
    spawn-animals: true
    on-join:
      title: ""
      subtitle: ""
    generator: ""
