name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} Plugin"
author: "BillyGalbreath"
api-version: "1.13"
softdepend:
  - CmdCD

commands:
  rtp:
    description: Teleport to a random location
    permission: command.rtp
    usage: /<command>
    aliases:
      - wild
      - wilderness
  setspawn:
    description: Set the servers main spawn
    permission: command.setspawn
    usage: /<command>
  spawn:
    description: Teleport to the servers main spawn
    permission: command.spawn
    usage: /<command>
  world:
    description: Teleport between worlds
    permission: command.world
    usage: /<command> [world]
  worldloader:
    description: Reload configs
    permission: command.worldloader
    usage: /<command> (reload)

permissions:
  command.rtp:
    description: Teleport to a random location
    default: op
  command.setspawn:
    description: Set the servers main spawn
    default: op
  command.spawn:
    description: Teleport to the servers main spawn
    default: true
  command.spawn.bypass.delay:
    description: Bypass the configured teleport delay for the /spawn command
    default: false
  command.world:
    description: Teleport between worlds
    default: op
  command.world.*:
    description: Allows teleporting to all worlds
    default: op
  command.worldloader:
    description: Allows to reload configs
    default: op
