name: "${project.artifactId}"
main: "${project.groupId}.${project.artifactId}"
version: "${project.version}"
description: "${project.artifactId} Plugin"
author: "BillyGalbreath"
api-version: "1.13"

commands:
  setspawn:
    description: Set the servers main spawn
    usage: /<command>
  spawn:
    description: Teleport to the servers main spawn
    usage: /<command>
  world:
    description: Teleport between worlds
    usage: /<command> [world]
  worldloader:
    description: Reload configs
    usage: /<command> (reload)

permissions:
  command.setspawn:
    description: Set the servers main spawn
    default: op
  command.spawn:
    description: Teleport to the servers main spawn
    default: true
  command.world:
    description: Teleport between worlds
    default: op
  command.world.*:
    description: Allows teleporting to all worlds
    default: op
  command.worldloader:
    description: Allows to reload configs
    default: op
